# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - planties-ai-dd-x86

on:
  push:
    branches:
      - docker
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_7cf4dc5d1c1740c1af50238b5c1ce9b5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_19ede3d2385b45108259bce9a8c9ed19 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7cf4dc5d1c1740c1af50238b5c1ce9b5 }}/whoisgalih/planties-ai-dd:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'planties-ai-dd-x86'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_87409081b9894e37ae52d54cb11c8593 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7cf4dc5d1c1740c1af50238b5c1ce9b5 }}/whoisgalih/planties-ai-dd:${{ github.sha }}'